### ISSUE TITLE
您好，请问这个脚本怎么使用呢？

### ISSUE THREAD

**Issue by QiHsMing** [Jerry-Terrasse/mi-solver#1]

**Comment by Jerry-Terrasse** [comment]
您好，`README.md`已更新

**Comment by QiHsMing** [comment]
> 您好，`README.md`已更新

谢谢，已看到更新内容，你的思路是通过记录答题的过程，来自行保存正确的答案。

请问这个项目也能支持”miui社区->内测中心->每日答题“ 吗？

还有一个问题，请问作者有多人共建、共享答案库的计划吗？毕竟一个人自行保存正确答案太慢了 0.0

**Comment by Jerry-Terrasse** [comment]
1. 不支持每日答题；
2. 我认为没有必要，网上流传的答案大差不差，只有少数几个题目模棱两可无法确定，我当时一会儿就排查完了；
3. 官方明确反对共享题库的存在，毕竟筛选出具有相应知识的人进入内测是内测答题的初衷。

**Comment by QiHsMing** [comment]
> 1. 不支持每日答题；
> 2. 我认为没有必要，网上流传的答案大差不差，只有少数几个题目模棱两可无法确定，我当时一会儿就排查完了；
> 3. 官方明确反对共享题库的存在，毕竟筛选出具有相应知识的人进入内测是内测答题的初衷。

好的，非常感谢！那我把这个issues close了
